# Generated by Django 3.1.6 on 2021-02-14 19:06

import crm.utils.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название')),
                ('address', models.TextField(default='', max_length=256, verbose_name='Адрес')),
                ('description', models.TextField(default='', max_length=2048, verbose_name='Описание')),
                ('start_of_construction', models.DateField(null=True, verbose_name='Начало строительства')),
                ('end_of_construction', models.DateField(null=True, verbose_name='Сдача')),
                ('count_lots', models.IntegerField(null=True, verbose_name='Количество лотов')),
                ('count_floors', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('infrastructure', models.TextField(blank=True, default='', max_length=2048, verbose_name='Инфраструктура')),
                ('transport_accessibility', models.TextField(blank=True, default='', max_length=2048, verbose_name='Транспортная доступность')),
                ('trim', models.CharField(blank=True, choices=[('Без отделки', 'Без отделки'), ('Черновая отделка', 'Черновая отделка'), ('Чистовая отделка', 'Чистовая отделка'), ('Готовая к заселению', 'Готовая к заселению')], max_length=128, verbose_name='Отделка')),
                ('facade', models.CharField(blank=True, default='', max_length=128, verbose_name='Фасад')),
                ('elevators', models.CharField(blank=True, default='', max_length=128, verbose_name='Лифты')),
                ('windows', models.CharField(blank=True, default='', max_length=128, verbose_name='Окна')),
                ('ventilation', models.CharField(blank=True, default='', max_length=128, verbose_name='Вентиляция')),
                ('conditioning', models.CharField(blank=True, default='', max_length=128, verbose_name='Кондиционирование')),
                ('cadastre', models.CharField(blank=True, default='', max_length=128, verbose_name='Кадастр')),
                ('tax', models.CharField(blank=True, default='', max_length=64, verbose_name='Налог')),
                ('content', models.TextField(blank=True, default='', max_length=512, verbose_name='Содержание')),
                ('contract', models.CharField(blank=True, default='', max_length=128, verbose_name='Договор')),
                ('ceilings', models.CharField(blank=True, default='', max_length=128, verbose_name='Потолки')),
                ('parking', models.CharField(blank=True, default='', max_length=128, verbose_name='Паркинг')),
                ('parking_price', models.CharField(blank=True, default='', max_length=64, verbose_name='Паркинг, р')),
                ('trade_registration', models.CharField(blank=True, default='', max_length=128, verbose_name='Регистрация сделки')),
                ('mortgage', models.CharField(blank=True, default='', max_length=128, verbose_name='Ипотека')),
                ('installment', models.CharField(blank=True, default='', max_length=128, verbose_name='Рассрочка')),
                ('promotions', models.CharField(blank=True, default='', max_length=256, verbose_name='Акции')),
                ('complex_infrastructure', models.CharField(blank=True, default='', max_length=256, verbose_name='Инфраструктура комплекса')),
                ('commercial_space', models.CharField(blank=True, default='', max_length=128, verbose_name='Коммерческие площади')),
                ('weekdays_from', models.IntegerField(blank=True, default=9, verbose_name='Будни с')),
                ('weekdays_to', models.IntegerField(blank=True, default=18, verbose_name='Будни по')),
                ('weekend_form', models.IntegerField(blank=True, default=9, verbose_name='Выходные с')),
                ('weekend_to', models.IntegerField(blank=True, default=18, verbose_name='Выходные по')),
                ('sales_office_address', models.TextField(blank=True, default='', max_length=256, verbose_name='Адрес офиса продаж')),
                ('note', models.TextField(blank=True, default='', max_length=516, verbose_name='Примечание')),
                ('parking_close', models.TextField(blank=True, default='', max_length=256, verbose_name='Паркинг')),
            ],
            options={
                'verbose_name': 'ЖК',
                'verbose_name_plural': 'ЖК',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Технология строительства')),
            ],
            options={
                'verbose_name': 'Технология строительства',
                'verbose_name_plural': 'Технологии строительства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название')),
                ('start_of_construction', models.DateField(null=True, verbose_name='Начало строительства')),
                ('end_of_construction', models.DateField(null=True, verbose_name='Сдача')),
                ('count_lots', models.IntegerField(null=True, verbose_name='Количество лотов')),
                ('count_floors', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='crm.complex', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпусы',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название')),
                ('plan', models.ImageField(blank=True, null=True, upload_to=crm.utils.base.images_upload_path, verbose_name='Планировка')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена')),
            ],
            options={
                'verbose_name': 'План этажа',
                'verbose_name_plural': 'Планы этажей',
            },
        ),
        migrations.CreateModel(
            name='ObjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Класс объекта')),
            ],
            options={
                'verbose_name': 'Класс объекта',
                'verbose_name_plural': 'Классы объектов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PremisesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Тип помещения')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, null=True, verbose_name='Название')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('plan', models.ImageField(upload_to=crm.utils.base.images_upload_path, verbose_name='План')),
                ('plan_floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='floors', to='crm.floor', verbose_name='Планировка этажа')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена')),
            ],
            options={
                'verbose_name': 'План помещения',
                'verbose_name_plural': 'Планы помещений',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Наименование')),
                ('status', models.CharField(choices=[('Продано', 'Продано'), ('Забронировано', 'Забронировано'), ('Свободно', 'Свободно')], default='Свободно', max_length=128, verbose_name='Статус')),
                ('lease', models.CharField(blank=True, default='', max_length=128, verbose_name='Сдача')),
                ('n_on_price', models.CharField(blank=True, default='', max_length=64, verbose_name='№ по прайсу')),
                ('floor', models.IntegerField(blank=True, default=0, verbose_name='Этаж')),
                ('s', models.FloatField(default=0, verbose_name='Площадь')),
                ('trim', models.CharField(choices=[('Без отделки', 'Без отделки'), ('Черновая отделка', 'Черновая отделка'), ('Чистовая отделка', 'Чистовая отделка'), ('Готовая к заселению', 'Готовая к заселению')], max_length=32, verbose_name='Отделка')),
                ('view_from_windows', models.CharField(choices=[('На улицу', 'На улицу'), ('Во двор', 'Во двор')], max_length=32, verbose_name='Вид из окон')),
                ('options', models.TextField(blank=True, default='', verbose_name='Опции')),
                ('reward', models.FloatField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('currency', models.CharField(blank=True, default='', max_length=32, verbose_name='Цена в валюте')),
                ('price', models.FloatField(default=0, verbose_name='Цена в руб.')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.complex', verbose_name='ЖК')),
                ('corp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.corp', verbose_name='Корпус')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.plan', verbose_name='План помещения')),
                ('type_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.premisestype', verbose_name='Тип объекта')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название')),
                ('link', models.CharField(blank=True, default='', max_length=128, verbose_name='Ссылка')),
                ('complex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.complex', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_from', models.IntegerField(default=0, verbose_name='Этаж с')),
                ('floor_to', models.IntegerField(default=0, verbose_name='Этаж по')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.complex', verbose_name='ЖК')),
                ('corp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.corp', verbose_name='Корпус')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.floor', verbose_name='Планировка эатажа')),
            ],
            options={
                'verbose_name': 'План этажа',
                'verbose_name_plural': 'Планы этажей',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=crm.utils.base.images_upload_path, verbose_name='Изображение')),
                ('complex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.complex', verbose_name='ЖК')),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.lot', verbose_name='Лот')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название')),
                ('file', models.FileField(max_length=512, upload_to=crm.utils.base.documents_upload_path, verbose_name='Файл')),
                ('type', models.CharField(choices=[('Презентация', 'Презентация'), ('Презентация без контактов', 'Презентация без контактов'), ('Цены', 'Цены'), ('Документы', 'Документы'), ('Прочее', 'Прочее')], max_length=64, verbose_name='Тип документа')),
                ('complex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.complex', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Наименование')),
                ('created_at', models.DateField(null=True, verbose_name='Дата основания')),
                ('description', models.TextField(blank=True, default='', max_length=2048, verbose_name='Описание')),
                ('objects_delivered', models.IntegerField(null=True, verbose_name='Сдано объектов')),
                ('objects_under_construction', models.IntegerField(null=True, verbose_name='Объектов строится')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='corp',
            name='premises_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.premisestype', verbose_name='Тип помещения'),
        ),
        migrations.AddField(
            model_name='corp',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, default='', max_length=128, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=64, verbose_name='E-mail')),
                ('note', models.CharField(blank=True, default='', max_length=256, verbose_name='Примечание')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='crm.complex', verbose_name='ЖК')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='crm.developer', verbose_name='Застройщик')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='complex',
            name='construction_tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.constructiontech', verbose_name='Технология строительства'),
        ),
        migrations.AddField(
            model_name='complex',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.developer', verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='complex',
            name='object_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.objectclass', verbose_name='Класс объекта'),
        ),
        migrations.AddField(
            model_name='complex',
            name='premises_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.premisestype', verbose_name='Тип помещения'),
        ),
        migrations.AddField(
            model_name='complex',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='complex',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена'),
        ),
    ]
