# Generated by Django 3.1.6 on 2021-02-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.lot', verbose_name='Лот'),
        ),
        migrations.AddField(
            model_name='document',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.lot', verbose_name='Лот'),
        ),
        migrations.AddField(
            model_name='link',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.lot', verbose_name='Лот'),
        ),
    ]
