# Generated by Django 3.1.6 on 2021-02-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_added_models_to_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='floors', to='crm.floor', verbose_name='Планировка этажа'),
        ),
    ]
