# Generated by Django 3.1.6 on 2021-02-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_floor_is_not_needs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corp',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={},
        ),
        migrations.RemoveField(
            model_name='lot',
            name='complex',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='corp',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='lease',
        ),
        migrations.AlterField(
            model_name='complex',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='crm.developer', verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='end_of_construction',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Сдача'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='start_of_construction',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Начало строительства'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.CharField(null=True, verbose_name='Дата основания'),
        ),
        migrations.CreateModel(
            name='OldBuildingLot',
            fields=[
                ('lot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.lot')),
                ('lease', models.CharField(blank=True, default='', max_length=128, verbose_name='Сдача')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_buildings', to='crm.complex', verbose_name='ЖК')),
                ('corp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.corp', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Вторичка',
                'verbose_name_plural': 'Вторички',
            },
            bases=('crm.lot',),
        ),
        migrations.CreateModel(
            name='NewBuildingLot',
            fields=[
                ('lot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.lot')),
                ('lease', models.CharField(blank=True, default='', max_length=128, verbose_name='Сдача')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_buildings', to='crm.complex', verbose_name='ЖК')),
                ('corp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.corp', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Новостройка',
                'verbose_name_plural': 'Новостройки',
            },
            bases=('crm.lot',),
        ),
    ]
