# Generated by Django 3.1.6 on 2021-02-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_vers055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='end_of_construction',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Сдача'),
        ),
        migrations.AlterField(
            model_name='corp',
            name='start_of_construction',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Начало строительства'),
        ),
    ]
