# Generated by Django 3.1.6 on 2021-03-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_vers056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['type'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='crm.developer', verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='end_of_construction',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Сдача'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='trim',
            field=models.CharField(blank=True, max_length=256, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='document',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='crm.complex', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='image',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='crm.complex', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='link',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='links', to='crm.complex', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.CharField(blank=True, choices=[('студия', 'студия'), ('с 1-ой спальней', 'с 1-ой спальней'), ('с 2-мя спальнями', 'с 2-мя спальнями'), ('с 3-мя спальнями', 'с 3-мя спальнями'), ('с 4-ой спальней', 'с 4-ой спальней')], max_length=252, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='trim',
            field=models.CharField(max_length=32, verbose_name='Отделка'),
        ),
    ]
