# Generated by Django 3.1.6 on 2021-03-28 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_vers09'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='near_metro',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Ближайшее метро'),
        ),
        migrations.AddField(
            model_name='complex',
            name='reward',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AddField(
            model_name='link',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.developer', verbose_name='застройщик'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='construction_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.constructiontech', verbose_name='Технология строительства'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='count_lots',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лотов'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='crm.developer', verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='object_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.objectclass', verbose_name='Класс объекта'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='premises_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.premisestype', verbose_name='Тип помещения'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.complex', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.developer', verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.lot', verbose_name='Лот'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена'),
        ),
        migrations.AlterField(
            model_name='document',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.complex', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='document',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.lot', verbose_name='Лот'),
        ),
        migrations.AlterField(
            model_name='image',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crm.complex', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='image',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crm.developer', verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='image',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crm.lot', verbose_name='Лот'),
        ),
        migrations.AlterField(
            model_name='link',
            name='complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crm.complex', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='link',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crm.lot', verbose_name='Лот'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='plan',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.plan', verbose_name='План помещения'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True, verbose_name='Наименование')),
                ('complex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='crm.complex', verbose_name='ЖК')),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='crm.lot', verbose_name='Лот')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
